# Generated by Django 5.2.1 on 2025-05-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_flightsindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="routepage",
            name="airlines_serving_route",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
