# Generated by Django 5.2.1 on 2025-05-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_routepage_airlines_serving_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="routepage",
            name="popular_routes",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
